### ISSUE TITLE
errors while setting up

### ISSUE THREAD

**Issue by mdbadawi** [contentacms/contenta_docker#13]
i got the following error after i ran  sudo docker-compose up -d :
`Service 'php' failed to build: The command '/bin/sh -c cd /usr/local/src &&     git clone https://github.com/contentacms/contenta_jsonapi &&     cd /usr/local/src/contenta_jsonapi &&     composer create-project contentacms/contenta-jsonapi-project /var/www --stability dev --no-interaction &&     cd /var/www &&     composer config repositories.contenta_jsonapi path .' returned a non-zero code: 1`

**Comment by pcambra** [comment]
Probably related with #18, please check that one and report back if it doesn't fix it
