### ISSUE TITLE
First-time initialization fails

### ISSUE THREAD

**Issue by DavidUnzue** [contentacms/contenta_docker#20]
I was able to build and start the docker container with no issues. All services are running as expected:
```
           Name                         Command               State                    Ports
--------------------------------------------------------------------------------------------------------------
contenta_docker_database_1   docker-entrypoint mysqld         Up      0.0.0.0:3306->3306/tcp
contenta_docker_nginx_1      container-entrypoint nginx       Up      0.0.0.0:443->443/tcp, 0.0.0.0:80->80/tcp
contenta_docker_php_1        docker-entrypoint /usr/sbi ...   Up      0.0.0.0:9000->9000/tcp
```

However, when trying to initialize the Drupal site like this:
```
docker exec contenta_docker_php_1 init-drupal
```

I get following error:
```
In BootstrapHook.php line 32:

  Bootstrap failed. Run your command with -vvv for more information.
```
 It seems there is an issue with Drush when calling:
```
drush si -y contenta_jsonapi --account-pass=test --db-url=mysql://$MYSQL_USER:$MYSQL_PASSWORD@database/$MYSQL_DATABASE
```

But I'm not able to find a solution. Also, I don't know that much about Drupal 8 and Drush...

**Comment by pcambra** [comment]
I can definitely reproduce the issue, looking to see if I can find out why it happens now, maybe drush related?

**Comment by e0ipso** [comment]
Ah! I think I know what that is. Maybe you can use the recommended installing method described in http://www.contentacms.org/#install

This will trigger this workaround: https://github.com/contentacms/contenta_jsonapi_project/blob/8.x-1.x/scripts/install.sh#L42-L59

**Comment by tgrandguillotte** [comment]
Same issue for me.
The script install.sh used by init-drupal already contain the workaround (the script is downloaded from the repo)
When I add the -vvv option to the drush command in the file /usr/local/bin/init-drupal I get this trace : 


```
bash-4.2# vi /usr/local/bin/init-drupal
bash-4.2# init-drupal
Generating RSA private key, 2048 bit long modulus
.................................................+++
.................................+++
e is 65537 (0x10001)
writing RSA key
 [preflight] Config paths: /var/www/vendor/drush/drush/drush.yml
 [preflight] Alias paths: /var/www/web/drush/sites,/var/www/drush/sites
 [preflight] Commandfile search paths: /var/www/vendor/drush/drush/src
 [bootstrap] Bootstrap to root [0.15 sec, 7.4 MB]

In BootstrapHook.php line 32:
                                                                      
  [Exception]                                                         
  Bootstrap failed. Run your command with -vvv for more information.  
                                                                      

Exception trace:
 Drush\Boot\BootstrapHook->initialize() at /var/www/vendor/consolidation/annotated-command/src/Hooks/Dispatchers/InitializeHookDispatcher.php:34
 Consolidation\AnnotatedCommand\Hooks\Dispatchers\InitializeHookDispatcher->callInitializeHook() at /var/www/vendor/consolidation/annotated-command/src/Hooks/Dispatchers/InitializeHookDispatcher.php:27
 Consolidation\AnnotatedCommand\Hooks\Dispatchers\InitializeHookDispatcher->initialize() at /var/www/vendor/consolidation/annotated-command/src/CommandProcessor.php:117
 Consolidation\AnnotatedCommand\CommandProcessor->initializeHook() at /var/www/vendor/consolidation/annotated-command/src/AnnotatedCommand.php:391
 Consolidation\AnnotatedCommand\AnnotatedCommand->initialize() at /var/www/vendor/symfony/console/Command/Command.php:217
 Symfony\Component\Console\Command\Command->run() at /var/www/vendor/symfony/console/Application.php:964
 Symfony\Component\Console\Application->doRunCommand() at /var/www/vendor/symfony/console/Application.php:248
 Symfony\Component\Console\Application->doRun() at /var/www/vendor/symfony/console/Application.php:148
 Symfony\Component\Console\Application->run() at /var/www/vendor/drush/drush/src/Runtime/Runtime.php:112
 Drush\Runtime\Runtime->doRun() at /var/www/vendor/drush/drush/src/Runtime/Runtime.php:41
 Drush\Runtime\Runtime->run() at /var/www/vendor/drush/drush/drush.php:66
 require() at /var/www/vendor/drush/drush/drush:4

site:install [--db-url DB-URL] [--db-prefix DB-PREFIX] [--db-su DB-SU] [--db-su-pw DB-SU-PW] [--account-name [ACCOUNT-NAME]] [--account-mail [ACCOUNT-MAIL]] [--site-mail [SITE-MAIL]] [--account-pass ACCOUNT-PASS] [--locale [LOCALE]] [--site-name [SITE-NAME]] [--site-pass SITE-PASS] [--sites-subdir SITES-SUBDIR] [--config-dir CONFIG-DIR] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-d|--debug] [-y|--yes] [--no] [--remote-host REMOTE-HOST] [--remote-user REMOTE-USER] [-r|--root ROOT] [-l|--uri URI] [--simulate] [--pipe] [-D|--define DEFINE] [--notify [NOTIFY]] [--druplicon] [--xh-link XH-LINK] [--] <command> [<profile>]...
```

**Comment by pcambra** [comment]
So I have some improvements in the repo that I'll be pushing later today, but I have a question for @e0ipso, in the install sh script, there's this duplicated install command that you're linking https://github.com/contentacms/contenta_jsonapi_project/blob/8.x-1.x/scripts/install.sh#L42

However, I can't really make this work as I think it's missing the name of the profile to install, so this
```
$DRUSH site-install --verbose --yes \
  --root=$DEST_DIR/$DOCROOT \
  --db-url=$DB_URL \
  --site-mail=$SITE_MAIL \
  --account-mail=$ACCOUNT_MAIL \
  --site-name=$SITE_NAME \
  --account-name=$ACCOUNT_NAME \
  --account-pass="$ACCOUNT_PASS";
```

Does not work as it complains about missing install profile name:

```
 [warning] The following profile is missing from the file system: CMS bootstrap.inc:276
 [warning] strpos(): Empty needle ExtensionDiscovery.php:295
 [warning] strpos(): Empty needle ExtensionDiscovery.php:295
 [warning] strpos(): Empty needle ExtensionDiscovery.php:295
 [warning] strpos(): Empty needle ExtensionDiscovery.php:295
 [warning] strpos(): Empty needle ExtensionDiscovery.php:295
 [warning] strpos(): Empty needle ExtensionDiscovery.php:295
 [warning] The following profile is missing from the file system: CMS bootstrap.inc:276
```

But if I do `bash-4.2# drush site-install contenta_jsonapi --verbose --yes   --root=$DEST_DIR/$DOCROOT   --db-url=$DB_URL   --site-mail=$SITE_MAIL   --account-mail=$ACCOUNT_MAIL   --site-name=$SITE_NAME   --account-name=$ACCOUNT_NAME   --account-pass="$ACCOUNT_PASS";` it works just fine

Wondering if I could create a PR for the install.sh script that adds the contenta_jsonapi profile, maybe that helps with having to install twice?

**Comment by e0ipso** [comment]
After *much* debugging, this should be fixed. I added the profile name to the drush call 🤦‍♂️ and provided a necessary fix in JSON API Extras.

I'd recommend following http://www.contentacms.org/#install in docker for this.

**Comment by pcambra** [comment]
Many thanks :)

I've modified the remainder of instructions and install process, it seems it is working but a second pair of 👀 would be good before closing this

**Comment by DavidUnzue** [comment]
Thank you all for checking this out. The installation is working for me as well, great! 🎉 

However, I noticed a couple of little issues that might be confusing for the user:

1. I don't see a one-time login URL after installation as stated in the readme.

2. The installer outputs a sentence with an empty admin password at the very end. The admin password is actually generated, but the hint is a couple of lines above. See screenshot below.

![image](https://user-images.githubusercontent.com/9588510/44977405-337ba180-af68-11e8-815e-fb20af5c83ed.png)

**Comment by pcambra** [comment]
Awesome, thanks for checking @DavidUnzue 

Regarding 1, good catch, maybe you could do a PR to clarify that in the readme?

About 2, I noticed it on install but to be completely honest, I don't know what the difference is between the two accounts (if any), maybe @e0ipso can throw some light on that

Maybe we could create separate issues for these two as the install is no longer failing and this one is fixed I think 👍

**Comment by tgrandguillotte** [comment]
Many thanks, it works fine now :)

**Comment by DavidUnzue** [comment]
@pcambra I created a PR that simply removes that sentence from the readme (https://github.com/contentacms/contenta_docker/pull/23).

Regarding the admin passwords, I created a separate issue whit a more in-depth description of the issue: https://github.com/contentacms/contenta_docker/issues/22

**Comment by pcambra** [comment]
We can close this one then thanks all! :)
