### ISSUE TITLE
Installation script: confusing message with empty admin password

### ISSUE THREAD

**Issue by DavidUnzue** [contentacms/contenta_docker#22]
Contenta creates a sample admin user during installation. The password for this user is retrieved from the environmental variables, which are located in the `.env` file (or the `.env.local` file, which does not exist in this repository). Here, the script `install.sh` looks for the variable `ACCOUNT_PASS` when running Drush's `site-install` command:
```
$DRUSH site-install contenta_jsonapi --verbose --yes \
  --root=$DEST_DIR/$DOCROOT \
  --db-url=$DB_URL \
  --site-mail=$SITE_MAIL \
  --account-mail=$ACCOUNT_MAIL \
  --site-name=$SITE_NAME \
  --account-name=$ACCOUNT_NAME \
  --account-pass="$ACCOUNT_PASS";
```

However, this variable doesn't exist in `.env`. Because of that, Drush will generate a random password for the admin user:
```
# https://github.com/drush-ops/drush/blob/9e82a30edc26208e3eaf20c9decf265d1f759a20/src/Commands/core/SiteInstallCommands.php#L82

$account_pass = $options['account-pass'] ?: StringUtils::generatePassword();
```

At the end of the installation, there are two different messages that get printed out to notify the user about the admin password:
- The first one is generated by Drush (https://github.com/drush-ops/drush/blob/9e82a30edc26208e3eaf20c9decf265d1f759a20/src/Commands/core/SiteInstallCommands.php#L146) only if no environmental variable was found and includes the randomly generated password.
- The second one is generated always by `install.sh` and shows the password form the environmental variable. If no one was supplied, then the message contains an empty password.

The whole thing looks like this:
![image](https://user-images.githubusercontent.com/9588510/45093097-ad9e5880-b117-11e8-8a6a-6ee7f9375bc3.png)

This behaviour can be confusing for the user, as they might think that no admin password was generated.

**Comment by pcambra** [comment]
That makes sense, maybe install.sh should only show that message when the env password is found? or we just add a default password in .env

**Comment by DavidUnzue** [comment]
I would suggest the second option, I created a PR (https://github.com/contentacms/contenta_docker/pull/24) that adds `admin` as default password to the env variables. This is the same default password used in the original Contenta repository:
https://github.com/contentacms/contenta_jsonapi/blob/a8cd75b38e42575460d2875f30a829eb186b21d2/scripts/development/build-contenta_jsonapi.sh#L64

It should be clear that `.env` is usually not the right place for secret variables like passwords (oposed to a local file like `.env.local`). But this is intended as a one-time password that should be changed afterwards, so it should be fine.

**Comment by pcambra** [comment]
Awesome, thanks for looking it up and provide a PR!
