### ISSUE TITLE
Jsonapi_extras broken

### ISSUE THREAD

**Issue by andrewfandrew** [contentacms/contenta_docker#27]
2 days ago I submitted a pull request. That was after I installed the repo locally and found that the site was broken. I isolated the problem to the jsonapi_extras module and tried a solution: downgrading it to v.2.10 from 2.11 (see my pull request). That fixed the site. I thought that this kind of event might happen again hence the pull request.

**Comment by pcambra** [comment]
I haven't seen this error, could you confirm 2.11 is still problematic? seems like something that could have been fixed upstream

**Comment by andrewfandrew** [comment]
Hi Pedro,
At the time of reporting it was broken, but i would not be surprised if it
has been fixed. Sorry not doing any work with Contenta just now.

Thanks,
Andrew

**Comment by pcambra** [comment]
Thanks Andrew, let's reopen if this happens again :)

**Comment by andrewfandrew** [comment]
😀 Okay.
