### ISSUE TITLE
Dropzone library missing

### ISSUE THREAD

**Issue by lrkwz** [contentacms/contenta_docker#28]
Fresh install, the `/admin/reports/status#error` shows:

    Dropzone library missing
    Dropzonejs requires the dropzone.min.js library. Download it (https://github.com/enyo/dropzone) and place it in the libraries folder (/libraries)

BTW I cannot find any `/libraries` folder. Maybe you should:

    curl -sL https://rpm.nodesource.com/setup_10.x | bash -
    sudo yum install -y nodejs

at the very beginning of the entrypoint or in Dockerfile.

**Comment by pcambra** [comment]
I think this is fixed upstream, feel free to reopen if it's not the case.
