### ISSUE TITLE
Development workflow advice

### ISSUE THREAD

**Issue by tanasi** [contentacms/contenta_docker#30]
Hi, 

using your steps I am able to create a working environment. The process will create a "www" folder in which there are a composer.json and composer.lock files. 

The question is: Typically somebody would want to commit those two files during development. Any advices on how to use this repo and have a continuous dev workflow?

e.g. Let's say that you add new packages with composer require, and commit those composer files. 
What should be the recommended workflow?
- clone the repo into a new folder
- docker-compose build
- docker-compose up
- install the content app
- copy the commited composer.json and composer.lock into www
- run composer install

**Comment by pcambra** [comment]
I'd say "freestyle" is the better option, there are other options such as ddev or lando to manage these workflows, this one would be much more manual, if that makes any sense. 

I'd say you could have the docker structure around the contenta project and commit the "composer stuff", but I know many people that also checks in vendor/modules.

**Comment by pcambra** [comment]
Closing this one, please feel free to reopen if it needs more info.
