### ISSUE TITLE
build of php fails

### ISSUE THREAD

**Issue by martinfrances107** [contentacms/contenta_docker#5]
I am following the instructions on 

https://github.com/contentacms/contenta_docker

a) git clone https://github.com/contentacms/contenta_docker.git
b) cd contenta_docker
c) docker-compose build

I see some warnings then an errors 

A) first, a notice really I am no using this repo....

Determining fastest mirrors
 * base: mirror.ox.ac.uk
 * extras: mirror.ox.ac.uk
 * updates: mirrors.coreix.net
Cannot open: http://rpms.remirepo.net/enterprise/remi-release-7.rpm. Skipping.

then further down the build output this warning 

B) Delta RPMs disabled because /usr/bin/applydeltarpm not installed.
warning: /var/cache/yum/x86_64/7/epel/packages/compat-libtidy-0.99.0-37.20091203.el7.x86_64.rpm: Header V3 RSA/SHA256 Signature, key ID 352c64e5: NOKEY

C) Then further down the output I am not sure why the  /var/lib/php/session/ file/dir does not exist which is the first ERROR I see 

Step 11/16 : RUN mkdir -p /var/www &&     fix-permissions /etc/php.ini &&     fix-permissions /etc/php-fpm.conf &&     fix-permissions /etc/php-fpm.d/ &&     fix-permissions /run/php-fpm &&     fix-permissions /var/www &&     fix-permissions /var/lib/php/session/ &&     chmod +x /usr/local/bin/docker-entrypoint &&     chmod +x /usr/local/bin/init-drupal
 ---> Running in e193e2e10ac3
ERROR: File or directory /var/lib/php/session/ does not exist.
Removing intermediate container e193e2e10ac3
 ---> 578540f8881e
Step 12/16 : RUN cd /usr/local/src &&     git clone https://github.com/contentacms/contenta_jsonapi &&     cd /usr/local/src/contenta_jsonapi &&     git checkout 836683de603741e9e3beebac1b047e34c684a69c &&     composer create-project contentacms/contenta-jsonapi-project /var/www --stability dev --no-interaction &&     cd /var/www &&     composer config repositories.contenta_jsonapi path .
 ---> Running in 9c842cac7f83
Cloning into 'contenta_jsonapi'...
Note: checking out '836683de603741e9e3beebac1b047e34c684a69c'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

HEAD is now at 836683d... Media improvements (#168)
    Finished: success: 0, skipped: 18, failure: 10, total: 28
    1/3:	http://packagist.org/p/provider-latest$605478410aad21fd77100bec77e2638100e1f58dd5c112e9a281ad7354cceaf8.json
    2/3:	http://packagist.org/p/provider-2017-07$400e158a9df018432a2f81f23aa5dfc8a2f1fb0fbd3f7fb8a1b9123daf3e8774.json
    3/3:	http://packagist.org/p/provider-2017-10$b8e128f0f9eecff70b746787f39fb64d736981af05fe3da53e4f9e5a4eced6da.json
    Finished: success: 3, skipped: 0, failure: 0, total: 3
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Installing contentacms/contenta-jsonapi-project (dev-8.x-1.x c7d88b10e5dc78427ac29ff1a036cf2b09ecbf70)

                                             
  [InvalidArgumentException]                 
  Project directory /var/www/ is not empty.  
                                             

create-project [-s|--stability STABILITY] [--prefer-source] [--prefer-dist] [--repository REPOSITORY] [--repository-url REPOSITORY-URL] [--dev] [--no-dev] [--no-custom-installers] [--no-scripts] [--no-progress] [--no-secure-http] [--keep-vcs] [--no-install] [--ignore-platform-reqs] [--] [<package>] [<directory>] [<version>]

ERROR: Service 'php' failed to build: The command '/bin/sh -c cd /usr/local/src &&     git clone https://github.com/contentacms/contenta_jsonapi &&     cd /usr/local/src/contenta_jsonapi &&     git checkout 836683de603741e9e3beebac1b047e34c684a69c &&     composer create-project contentacms/contenta-jsonapi-project /var/www --stability dev --no-interaction &&     cd /var/www &&     composer config repositories.contenta_jsonapi path .' returned a non-zero code: 1

**Comment by martinfrances107** [comment]
I have cleared some errors in my local build, listed below is the response to the 

composer create-project contentacms/contenta-jsonapi-project /var/www --stability dev --no-interaction

In short we need to upgrade from PHP 5.4.16  to something modern say php71? 


    Finished: success: 0, skipped: 18, failure: 10, total: 28
    1/2:	http://packagist.org/p/provider-latest$33d3bbe35e0823b27c1039003573018d68f03fe91a739501ad3c032e6a224daf.json
    2/2:	http://packagist.org/p/provider-2017-10$b2dbb0ab94ff70bf3574011e3fd2d2801a46b7290971cad19e7bbcfcbe20d104.json
    Finished: success: 2, skipped: 0, failure: 0, total: 2
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Installing contentacms/contenta-jsonapi-project (dev-8.x-1.x c7d88b10e5dc78427ac29ff1a036cf2b09ecbf70)
  - Installing contentacms/contenta-jsonapi-project (dev-8.x-1.x 8.x-1.x): Cloning 8.x-1.x
Created project in /var/www
    Finished: success: 0, skipped: 0, failure: 28, total: 28
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - drupal/core 8.5.x-dev requires php >=5.5.9 -> your PHP version (5.4.16) does not satisfy that requirement.
    - drupal/core 8.4.x-dev requires php >=5.5.9 -> your PHP version (5.4.16) does not satisfy that requirement.
    - drupal/core 8.4.4 requires php >=5.5.9 -> your PHP version (5.4.16) does not satisfy that requirement.
    - drupal/core 8.4.3 requires php >=5.5.9 -> your PHP version (5.4.16) does not satisfy that requirement.
    - drupal/core 8.4.2 requires php >=5.5.9 -> your PHP version (5.4.16) does not satisfy that requirement.
    - contentacms/contenta_jsonapi dev-8.x-1.x requires drupal/core ^8.4.2 -> satisfiable by drupal/core[8.4.2, 8.4.3, 8.4.4, 8.4.x-dev, 8.5.x-dev].
    - Installation request for contentacms/contenta_jsonapi dev-8.x-1.x -> satisfiable by contentacms/contenta_jsonapi[dev-8.x-1.x].

**Comment by martinfrances107** [comment]
I have provided a solution to the problem in the pull request above .. it is a single line fix.

I hope this helps.

**Comment by pcambra** [comment]
Somehow this must have changed recently as it was working with php 7 before... strange. Anyway, many thanks for the PRs!
