### ISSUE TITLE
#7 contenta_json_api checks out master branch

### ISSUE THREAD

**Issue by martinfrances107** [contentacms/contenta_docker#7]
we currently use a old version of contenta_jsonapi

Related to contenta_jsonapi the dockerfile has this line

> git checkout 836683de603741e9e3beebac1b047e34c684a69c

using the command below from the 1.449 tag version  --- to show how many commits have been made

git rev-list --count 836683de603741e9e3beebac1b047e34c684a69c

280

280 commits behind ... I  suggest it is time to upgrade. I am working on this now and will 
create a pull request soon.

**Comment by martinfrances107** [comment]
The pull request shown above is clean.

I have been playing around with the modified site for about 12 hours and did not see any bugs.

**Comment by martinfrances107** [comment]
Based on a suggestion by @e0ipso 

I have make the changes so that we now checkout the latest tagged version

https://github.com/martinfrances107/contenta_docker

**Comment by pcambra** [comment]
Depending on what we want for this "profile", if it's targeted to users to try contenta out for evaluation, latest stable is the way to go, however, if this is a development tool, maybe master would make more sense?

**Comment by martinfrances107** [comment]
Managing the expectations of new users it tricky...

your development tool argument is fine.

My perspective from just a few days ago is different. As a contenta newbie just looking things inspect the state of the project. I would have steered away from a development tool. -- I really just wanted to see something stable in the first introductory hour. 

Perhaps other people can comment ... Maybe the solution is to have 

A) two clearly labelled branches. master/stable.

 OR 

B) the options to specify LATEST/MASTER in an environment variable inside the docker-compose.yml file.

Anyway I need to sort out the sendmail issue and clean up the comments in the PR. So I will sort those out first.

**Comment by martinfrances107** [comment]
@e0ipso 

has commented elsewhere that checking out to master is fine ... so I have updated the PR

**Comment by martinfrances107** [comment]
🎉
