### ISSUE TITLE
Upgrade to php71

### ISSUE THREAD

**Issue by martinfrances107** [contentacms/contenta_docker#9]
In other environments, I have noticed moderate performance  improvements upgrading to php71.

Performance is complicated, but in other projects I observed time to first byte for the HTML improved about 5%.. nothing great but nothing to sneer about.

So I think it is by default a good thing to do. I have done a little test all seems ok.

looking at /admin/reports/status/php --- show the php version being used is 7.1.13

I am about to create a pull request.

**Comment by martinfrances107** [comment]
Here is the pull request.

**Comment by martinfrances107** [comment]
The PR Is bad because it assumes the PR from #7 

I will update the PR when I have addressed the feedback in the other issue.

**Comment by pcambra** [comment]
👍

**Comment by pcambra** [comment]
Many thanks!
